// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2plIiVJVhQz1aYRFU_JpkQvEG9Adk_o',
    appId: '1:809872620716:web:ce6088ac479492895db309',
    messagingSenderId: '809872620716',
    projectId: 'led-final-test',
    authDomain: 'led-final-test.firebaseapp.com',
    storageBucket: 'led-final-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxc9rhOnGTfVKwY-ZSmzyg79FoAO4lphw',
    appId: '1:809872620716:android:6a6ac27e045ec19e5db309',
    messagingSenderId: '809872620716',
    projectId: 'led-final-test',
    storageBucket: 'led-final-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtt5v5XTPGp_HKFrvKmM1dMeTXjT87j9k',
    appId: '1:809872620716:ios:bc926b858f0e32795db309',
    messagingSenderId: '809872620716',
    projectId: 'led-final-test',
    storageBucket: 'led-final-test.firebasestorage.app',
    iosBundleId: 'com.example.appLed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtt5v5XTPGp_HKFrvKmM1dMeTXjT87j9k',
    appId: '1:809872620716:ios:bc926b858f0e32795db309',
    messagingSenderId: '809872620716',
    projectId: 'led-final-test',
    storageBucket: 'led-final-test.firebasestorage.app',
    iosBundleId: 'com.example.appLed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa2plIiVJVhQz1aYRFU_JpkQvEG9Adk_o',
    appId: '1:809872620716:web:4e09f86f69f70aef5db309',
    messagingSenderId: '809872620716',
    projectId: 'led-final-test',
    authDomain: 'led-final-test.firebaseapp.com',
    storageBucket: 'led-final-test.firebasestorage.app',
  );
}
